### ISSUE TITLE
How do we handle versions of workflow specifications?

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cm-cicada#12]
현재 [워크플로우 예제](https://github.com/cloud-barista/cm-cicada/blob/main/lib/airflow/example/workflow_template/create_infra_workflow.json)에는 해당 워크플로우 명세/규격의 버전 정보가 따로 명시되어 있지 않은 것으로 보입니다.

워크플로우의 지원 기능 변화 등에 따라 필드가 추가되거나 삭제되는 등 지속적으로 업데이트가 될 것으로 예상되기에 워크플로우 명세/규격 자체에 대한 버전 관리가 필요할 것으로 생각됩니다.

예를 들어 HTML의 경우 1.0부터 최근 5.2 까지 규격 자체에 대한 버전 관리를 하고 있고, 쿠버네티스의 경우 각 오브젝트의 API 버전(apiVersion)을 기술하여 버전에 따라 해당 요청 내용을 검증하거나 버전에 따라 동작하고 있습니다.

이러한 형태로 워크플로우 명세/규격 자체에 대한 버전 정의 및 관리 할 수 있는 방안이 필요해 보입니다.
워크플로우 규격과 GUI와의 연관성이나 현재 활용 중이 gusty 등과의 연관성 검토도 필요해 보입니다.

@ish-hcc

**Comment by ish-hcc** [comment]
@sykim-etri
감사합니다 버전을 사용하는 부분에 대해 이해되었습니다, 말씀해 주신대로 Airflow와 gusty의 변화도 고려해서 버전을 지정할 수 있도록 하겠습니다.

**Comment by ish-hcc** [comment]
@sykim-etri 
https://github.com/cloud-barista/cm-cicada/commit/a3745053a0f8c055fb49e9a795662445168c3625
해당 커밋 이후로 워크플로우의 규격에 대한 버전 명시가 가능해 짐에 따라 이슈를 종료합니다
