### ISSUE TITLE
Defining Terms and Operating Mechanisms within C-Migrator's Workflow

### ISSUE THREAD

**Issue by MZC-CSC** [cloud-barista/cm-cicada#3]
Defining Terms and Operating Mechanisms within C-Migrator's Workflow

Workflow에서 사용하는 용어
workflow, workflow-template, task, task-template 과

api호출 시 요구되는 request Param 에 대하여 정의 및 사용방법 정리된 내용 설명부탁드립니다.

----
기본적인 흐름이 맞는지 정리된 내용 한번 더 검토바랍니다.

task template 은 swagger를 참조하여
대상 api의 request object를 기반으로 cicada에서
task_template을 정의한다.

webconsole에서는 task_template의 정보로 바탕으로 data를 set 하여
cicada에 workflow로 저장한다.
(1 task = n operation이 되더라도
param_option 부분만 바라볼 수 있으면 될 것 같습니다.)

workflow안에 task_template추가하여 사용한 task_template이 무엇인지 확인할 수 있다.

**Comment by ish-hcc** [comment]
- param 옵션들은 다음 항목에 정의 : `param_option`
- beetle을 대상으로 한 SimpleHttpOperator 기반 Task Template 예시 참고
https://github.com/cloud-barista/cm-cicada/blob/main/lib/airflow/example/task_template/beetle_task_infra_migration.json
- echo 명령어를 실행하는 BashOperator 기반 Task Template 예시 참고
https://github.com/cloud-barista/cm-cicada/blob/main/lib/airflow/example/task_template/bash_task_echo.json

### param_option 내의 항목들에 대한 설명
- operator_option_for_use_as_param: 사용자로 부터 얻은 param들을 가지고 Task에서 실제로 요청을 하기위해 Operator의 옵션으로 사용되는 부분
  - SimpleHttpOperator의 경우 HTTP요청을 위해 JSON형태의 data 라는 옵션을 필요로 함.
  - BashOperator의 경우 명령어 실행을 위해 String형태의 bash_command 라는 옵션을 필요로 함.
- operator_option_value_is_json: operator_option_for_use_as_param에 명시한 Operator 옵션에 들어갈 값이 JSON 형태인지 여부
  - SimpleHttpOperator의 경우 사용되는 data 라는 옵션은 JSON 형태이기에 true 로 설정
  - BashOperator의 경우 사용되는 bash_command 라는 옵션은 String 형태이기에 false 로 설정
- params: 대상 API의 Swagger를 참고
  - Beetle의 경우 아래 swagger.json의 controller.MigrateInfraReques를 참고
    https://github.com/cloud-barista/cm-beetle/blob/main/pkg/api/rest/docs/swagger.json#L1235C10-L1235C39
  - required: Swagger의 required와 동일
  - properties: Swagger의 properties 기반으로 작성. type이 array인 경우 하위에 required 와 properties 항목이 존재

### Web에서 Workflow 및 Task 작성시 참조 방법
1. Workflow 작성을 위해 Workflow Template 선택
2. 선택된 Workflow Template 호출
3. Workflow Template 내 Task 들마다 명시되어있는 Task Template 참조
4. 해당 Task Template을 기반으로 Task에서 필요한 Param들 설정
5. 실행을 위한 Workflow로 저장 또는 새로운 Workflow Template 으로 저장

**Comment by ish-hcc** [comment]
Task Template -> Task Component 로 이름 변경
